dist: xenial # default 2019-09-01
sudo: false # build faster?
language: java
jdk:
  - openjdk8
  - openjdk11

git:
  depth: 3
  quiet: true

env:
  global:
    - MAVEN_BUILD_ARGS="-DskipTests=false -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B -V -T 2.0C"
    - BUILD_DOCKER=true

before_install:
  - chmod +x mvnw

install: skip

script:
  - ./mvnw clean install $MAVEN_BUILD_ARGS
  - |
    if [ "$BUILD_DOCKER" = "true" ]; then
      echo "Build docker..."
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
